### ISSUE TITLE
使用morjs后 vant-weapp popup 无遮罩，close-on-click-overlay	不生效

### ISSUE THREAD

**Issue by Elaine-X** [eleme/morjs#106]

**Comment by BboyZaki** [comment]
微信小程序吗？我这未能复现该问题

**Comment by Elaine-X** [comment]
转为抖音小程序后，就会失效
微信小程序正常

**Comment by Elaine-X** [comment]
> 微信小程序吗？我这未能复现该问题，请提供一个最小的可复现 demo

微信原生小程序转字节小程序，遇见以下几个问题
1. 使用vant-weapp UI库，popup无遮罩、close-on-click-overlay 不生效，tabs直接没了
2. pageScrollTo失效（scroll-view中直接指定scroll-top也失效）

**Comment by BboyZaki** [comment]
> > 微信小程序吗？我这未能复现该问题，请提供一个最小的可复现 demo
> 
> 微信原生小程序转字节小程序，遇见以下几个问题
> 
> 1. 使用vant-weapp UI库，popup无遮罩、close-on-click-overlay 不生效，tabs直接没了
> 2. pageScrollTo失效（scroll-view中直接指定scroll-top也失效）

刚查了下产物，popup 引用了 overlay 组件，overlay 引用了 transition 组件

导致遮罩不显示的原因是：overlay 组件里的 .van-overlay 样式在 transition 组件里未生效，间接导致了 close-on-click-overlay 事件无法触发（.van-overlay 样式里有元素的宽高）
按照抖音文档，样式是会从组件外继承到组件内（抖音小程序没有样式隔离选项），目前实测该 Bug 仍存在

修复方案：
1. 快速修复：将 .van-overlay 样式在 transition 组件的 *css 样式文件中复写一份
2. 等待抖音官方修复【组件无法继承组件外 class 样式】的问题

**Comment by Elaine-X** [comment]
> > > 微信小程序吗？我这未能复现该问题，请提供一个最小的可复现 demo
> > 
> > 
> > 微信原生小程序转字节小程序，遇见以下几个问题
> > 
> > 1. 使用vant-weapp UI库，popup无遮罩、close-on-click-overlay 不生效，tabs直接没了
> > 2. pageScrollTo失效（scroll-view中直接指定scroll-top也失效）
> 
> 刚查了下产物，popup 引用了 overlay 组件，overlay 引用了 transition 组件
> 
> 导致遮罩不显示的原因是：overlay 组件里的 .van-overlay 样式在 transition 组件里未生效，间接导致了 close-on-click-overlay 事件无法触发（.van-overlay 样式里有元素的宽高） 按照抖音文档，样式是会从组件外继承到组件内（抖音小程序没有样式隔离选项），目前实测该 Bug 仍存在
> 
> 修复方案：
> 
> 1. 快速修复：将 .van-overlay 样式在 transition 组件的 *css 样式文件中复写一份
> 2. 等待抖音官方修复【组件无法继承组件外 class 样式】的问题

好的，感谢

**Comment by BboyZaki** [comment]
已咨询过抖音开发者，他们下个基础库版本（2.99）会支持 组件样式隔离配置 styleIsolation
