### ISSUE TITLE
MorJS 和 uni-app 相比能说下它的优势是那里，或者它改进了什么?

### ISSUE THREAD

**Issue by hangjob** [eleme/morjs#115]
今天刚进网站，看到这些个
![image](https://github.com/eleme/morjs/assets/22078920/6ac18d43-63ce-4252-bf6d-91ac7980d83f)

**Comment by hwaphon** [comment]
用一句话来概括：你可以直接给支付宝小程序 or 微信小程序 赋予跨端的能力，即基于小程序 DSL。

详情参考 [MorJS 介绍](https://mor.eleme.io/guides/)
