### ISSUE TITLE
地图API问题

### ISSUE THREAD

**Issue by qizikuai** [eleme/morjs#120]
微信转支付宝时，地图API存在问题：
地图的polygons属性帮忙看看是不是转化有问题，微信polygons转化之后还是polygons，支付宝官方是polygon，而不是polygon**s**

**Comment by qizikuai** [comment]
![image](https://github.com/eleme/morjs/assets/34884728/b78f60d0-2281-4005-ba91-5e5a074b84ee)

**Comment by hwaphon** [comment]
已在 [V1.0.85](https://github.com/eleme/morjs/releases/tag/v1.0.85) 版本中修复~
