### ISSUE TITLE
这个和uniapp有什么区别么

### ISSUE THREAD

**Issue by bbhxwl** [eleme/morjs#128]
rt

**Comment by hwaphon** [comment]
Mor (发音为 /mɔːr/，类似 more) 是饿了么开发的一款**基于小程序 DSL** 的，可扩展的多端研发框架。使用**小程序原生 DSL** 构建，使用者只需书写一套（微信或支付宝）小程序，就可以通过 Mor 的转端编译能力，将源码分别编译出可以在不同端（微信/支付宝/百度/字节/钉钉/快手/QQ/淘宝/H5…）运行的产物。
