### ISSUE TITLE
src目录增加utils文件夹,编译后不见了, 

### ISSUE THREAD

**Issue by duxxz** [eleme/morjs#129]
src目录增加其他目录代码, assets目录增加非图片资源(.svga | .wasm | .gif), 编译之后, 小程序没有这些文件了, 应该怎么配置呢

**Comment by hwaphon** [comment]
试了一下上述的场景，编译之后 assets 文件夹下原资源仍然存在(见下图)，如果你仍然有问题，可以提供一个最小可还原的示例工程。

![image](https://gw.alicdn.com/imgextra/i1/O1CN01vWRNHe25CvpR62p9r_!!6000000007491-0-tps-579-1022.jpg)

**Comment by duxxz** [comment]
> 试了一下上述的场景，编译之后 assets 文件夹下原资源仍然存在(见下图)，如果你仍然有问题，可以提供一个最小可还原的示例工程。
> 
> ![image](https://camo.githubusercontent.com/8eb509c5f8eb44b77d1405f13c9f0fc413052e9f3d73b0ad7dbfdb5cca8d793f/68747470733a2f2f67772e616c6963646e2e636f6d2f696d6765787472612f69312f4f31434e30317657524e486532354376705236327039725f2121363030303030303030373439312d302d7470732d3537392d313032322e6a7067)

![image](https://github.com/eleme/morjs/assets/6425288/2b2d0556-f228-48e5-ab34-c7f8c12e5358)

真没有. 打包的淘宝的

**Comment by duxxz** [comment]
![微信截图_20231121155051](https://github.com/eleme/morjs/assets/6425288/743434e4-69f3-467a-bfbc-9484f2990794)
![微信截图_20231121155106](https://github.com/eleme/morjs/assets/6425288/5bb84078-4d1c-41d4-8255-777bfe65af91)
没有的, 编译的淘宝的小程序

**Comment by duxxz** [comment]
![微信截图_20231121155051](https://github.com/eleme/morjs/assets/6425288/381088a0-3ab5-4826-86b9-5f66664315e6)
![微信截图_20231121155106](https://github.com/eleme/morjs/assets/6425288/9e3c4783-8af9-4c20-90b5-8e3c030dfbdf)
真的没有, 打包的淘宝的小程序, 是不是有这个原因呢, sourceType是alipay

**Comment by duxxz** [comment]
> 试了一下上述的场景，编译之后 assets 文件夹下原资源仍然存在(见下图)，如果你仍然有问题，可以提供一个最小可还原的示例工程。
> 可以用这个试试
https://github.com/duxxz/morjsTest

**Comment by hwaphon** [comment]
这种尾缀的文件，mor 默认不会做复制，只有下述尾缀的文件会做复制👇🏻:
![image](https://github.com/eleme/morjs/assets/13358140/d1f9b760-ba46-45ab-bb99-b00e4c5a411c)

对不会默认复制的文件，可以使用  [copy 配置](https://mor.eleme.io/guides/basic/config/#copy---%E6%96%87%E4%BB%B6%E6%8B%B7%E8%B4%9D)

举个例子（复制 assets/bg_changed_transition.svga 文件）

![image](https://github.com/eleme/morjs/assets/13358140/4ce63752-35c2-48e1-bde0-fe0b072322b3)
