### ISSUE TITLE
vant 打包下 wxs 依赖缺失问题

### ISSUE THREAD

**Issue by yzend** [eleme/morjs#133]
**Describe the bug**
在使用vantui库时候，如果主包引用了 一个 vant-a组件，子包引用vant-b组件（需要是notice这类wxs还依赖公共wxs的组件），这个时候进行 build，产物中，子包的npm_package 中 vant缺少公共的wxs文件导致 函数不存在。

**To Reproduce**
初始化项目，添加 @vant/weapp
在主页面 pages/index 下引入 vant-icon
在子包页面中 src/subPackages/subPackage1/demo 中添加 van-notice-bar组件
然后执行 compile
子包的npm_components下 vant的 van-notice-bar 组件缺少公共的 wxs引入

**Expected behavior**
将公用的 wxs引入到子包的 npm_components中 或者 针对van这类ui组件同一放在 主包的 npm_components中

**Screenshots**
![image](https://github.com/eleme/morjs/assets/38238326/a18f31d4-fb8d-4407-b4cd-7b3cafcbe9c0)

代码示例
[myapp.zip](https://github.com/eleme/morjs/files/13594442/myapp.zip)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hwaphon** [comment]
https://github.com/eleme/morjs/releases/tag/v1.0.91

V1.0.91 版本已修复

**Comment by nile52** [comment]
morjs+vant weapp，可以运行在web端吗
