### ISSUE TITLE
微信DSL编译产出支付宝小程序配置不生效问题

### ISSUE THREAD

**Issue by Rainbow0728** [eleme/morjs#140]
**Describe the bug**
源项目是微信小程序，编译产出支付宝小程序，想禁用页面参数自动解码能力，在支付宝小程序app.son如下配置不生效
```
// app.json
{
  "behavior": {
    // 当设置为disable时，基础库解析全局参数、页面参数时不再对键/值做 decodeURIComponent
    "decodeQuery": "disable"
  }
}
```

跳转前对参数进行encodeURIComponent
![image](https://github.com/eleme/morjs/assets/22463187/200f9f57-e5ca-4f4d-a420-b76463e964f2)
在跳转目标页面接收参数没有做任何处理，参数还是被自动解码了
![image](https://github.com/eleme/morjs/assets/22463187/638e6681-645e-4926-90e3-998ff5448cdb)
![image](https://github.com/eleme/morjs/assets/22463187/2fd3f3f6-fc5c-4110-929f-186c38114e8b)

我通过支付宝小程序IDE直接创建支付宝小程序，添加配置，同样的代码，此时配置是生效的
![image](https://github.com/eleme/morjs/assets/22463187/a21a5c56-24fe-4278-a924-c58c384c5854)

**Comment by hwaphon** [comment]
用户反馈在IDE开启 components 2.0 配置已生效。
