### ISSUE TITLE
使用了微信小程序比较流行的日历组件，但转换过程却不行。

### ISSUE THREAD

**Issue by cailiangmu** [eleme/morjs#143]
日历组件地址 ：https://github.com/treadpit/wx_calendar  。组件实际内容见附件
[v2.zip](https://github.com/eleme/morjs/files/13790657/v2.zip)

引用页面： "usingComponents": {
    "calendar": "../../component/v2/index"
  }
实际渲染出来的是
<component is="component/v2/index" id="calendar" config="[object Object]" morTagId="calendar" morTagName="calendar" onOnSwipe="onSwipe" onTakeoverTap="takeoverTap" onAfterTapDate="afterTapDate" onWhenChangeMonth="whenChangeMonth" onAfterCalendarRender="afterCalendarRender"></component>
并不是实际日历绘制出的内容。

**Comment by hwaphon** [comment]
使用 mor init 创建工程，使用该组件正常，请确认是否被工程其它配置影响。
