### ISSUE TITLE
使用 vant 组件会报错。

### ISSUE THREAD

**Issue by DiamondYuan** [eleme/morjs#144]
## 复现 demo
https://github.com/DiamondYuan/ant-design-mini-reproduce/tree/main/mor-vant-tabs

## 根源是组件的  observer 与生命周期方法的触发顺序不一致。

复现 demo: https://github.com/DiamondYuan/ant-design-mini-reproduce/tree/main/behavior

**Comment by hwaphon** [comment]
已解决
