### ISSUE TITLE
使用微信DSL开发组件转到web时，observers的触发早于组件的created生命周期.

### ISSUE THREAD

**Issue by penduan** [eleme/morjs#154]
**使用微信DSL开发转web时，observers的触发早于组件的生命周期created.**
由于一些逻辑和方法会封装在组件created事件内（例如tdesign就是），但转换到web时，observers内的事件触发早于组件的created触发。

**Comment by hwaphon** [comment]
在 1.0.95 版本修复过微信转支付宝场景下 observer 属性和 created 生命周期顺序的问题，observers 还未支持，预计在 1 月底左右修复。
