### ISSUE TITLE
编译后分包中js文件在主包中无法引入使用

### ISSUE THREAD

**Issue by Rainbow0728** [eleme/morjs#157]
使用微信DSL开发，在js文件中预置数据，放在分包中，编译后主包中无法引用js文件
编译前
![image](https://github.com/eleme/morjs/assets/22463187/44a405fb-78dd-40d2-bd38-0b8e29c261b4)
编译后
![image](https://github.com/eleme/morjs/assets/22463187/66ed692f-6c5c-49cf-bc55-329ed030e5d8)
抖音小程序运行提示
![image](https://github.com/eleme/morjs/assets/22463187/d993dad1-479f-4658-ade0-2415f869de4f)
微信小程序提示
![image](https://github.com/eleme/morjs/assets/22463187/e452ff21-d1b0-43f3-8551-915d571cae6d)

**Comment by hwaphon** [comment]
已提供解决方案。
