### ISSUE TITLE
支付转微信, 定义的props无法正常使用

### ISSUE THREAD

**Issue by duxxz** [eleme/morjs#162]
支付宝转微信
![image](https://github.com/eleme/morjs/assets/6425288/03577201-fed8-4bf3-9abb-536707cf276c)
自定义组件
![image](https://github.com/eleme/morjs/assets/6425288/2a30183c-b0ba-4667-9d96-8b75c796f3f7)
报错
![image](https://github.com/eleme/morjs/assets/6425288/7c8ac51c-c074-4a7d-89c9-67bb5e9c34a2)

**Comment by hwaphon** [comment]
我这里是正常的，请提供一个可还原的示例
