### ISSUE TITLE
wComponent 转支付宝后 observer 执行问题

### ISSUE THREAD

**Issue by Tuuu** [eleme/morjs#23]
**问题描述**
wComponent 转支付宝后，组件接受 a, b 两个 properties 而且都有 observer，转到支付宝之后，父组件改变 a 的值的情况下，b 的 observer 也会执行。预期：应该只执行 a 的 observer

**环境信息**
```
@morjs/cli => 1.0.27
@morjs/core => 1.0.11
node_version => v16.15.1
yarn => 1.22.19
OS => MAC OS 12.4
```

**Comment by BboyZaki** [comment]
1.0.35 中已修复，请更新 @morjs/cli
