### ISSUE TITLE
Can't resolve '@vant/weapp/popup/index'

### ISSUE THREAD

**Issue by qiphon** [eleme/morjs#24]
vant 路径解析错误

src/pages/index/index.json
```json
{
  "usingComponents": {
    "van-popup": "@vant/weapp/popup/index",
    "wxml-to-canvas": "wxml-to-canvas",
    "van-field": "@vant/weapp/field/index",
    "select": "../../components/select/index"
  }
}
```
mor.config.ts
```ts
import { defineConfig } from '@morjs/cli';
import path from 'path';

export default defineConfig(
  [
    {
      name: 'wechat',
      sourceType: 'wechat',
      target: 'web',
    },
    // {
    //   name: 'wechat',
    //   sourceType: 'wechat',
    //   target: 'wechat',
    // },
  ].map(cfg => {
    return {
      ...cfg,
      alias: {
        '@vant/weapp/': path.join(
          __dirname,
          './src/miniprogram_npm/@vant/weapp/',
        ),
      },
    };
  }),
);


```

执行命令
mor compile -w  

error : 

Can't resolve '@vant/weapp/popup/index' in '/Users/u/Desktop/project/src/pages/index'

[mor] ✖ ⁃ finishWithoutResolve
             node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:309

**Comment by qiphon** [comment]
alias  path.join 改为 path.resolve  之后出现了新的问题

[mor] ✖ 编译 ../node_modules/.pnpm/@vant+weapp@1.10.5/node_modules/@vant/weapp/lib/field/index.js 失败:
        => Module not found: Error: Can't resolve './index.axml' in '/Users/u/Desktop/project/node_modules/.pnpm/@vant+weapp@1.10.5/node_modules/@vant/weapp/lib/field'

**Comment by lyfeyaj** [comment]
可以按照如下步骤尝试：

1. 确保 MorJS 相关依赖为最新版本
2. 在转 Web 的配置项中开启 `processNodeModules` 配置，确保 `@vant/weapp` 可以正确编译
3. 去掉 alias 配置，并在项目中直接按照实际路径引用，比如： "@vant/weapp/lib/popup/index"
