### ISSUE TITLE
不支持 model:value

### ISSUE THREAD

**Issue by andylei18** [eleme/morjs#30]
**Describe the bug**
Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.

<tiga-input class={"new-todo"} model:value={$rm.toJsonString(todoTitle, false)} placeholder={"What needs to be done?"} autofocus />

**To Reproduce**
如上描述

**Expected behavior**
可支持，因为微信官方支持：https://developers.weixin.qq.com/miniprogram/dev/framework/view/two-way-bindings.html

**Screenshots**
![image](https://user-images.githubusercontent.com/8412644/234517075-f688e01f-7e0f-4693-90d2-366bdd1a5929.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andylei18** [comment]
mor配置如下：
import { defineConfig } from '@morjs/cli'

export default defineConfig([
  {
    name: 'wechat-miniprogram',
    sourceType: 'wechat',
    target: 'wechat',
    compileType: 'miniprogram',
    compileMode: 'bundle'
  },
  {
    name: 'alipay-miniprogram',
    sourceType: 'wechat',
    target: 'alipay',
    compileType: 'miniprogram',
    compileMode: 'bundle'
  },
  {
    name: 'tt-miniprogram',
    sourceType: 'wechat',
    target: 'bytedance',
    compileType: 'miniprogram',
    compileMode: 'bundle'
  },
  {
    name: 'web',
    sourceType: 'wechat',
    // outputPath: './h5_dist/lib',
    target: 'web',
    compileType: 'miniprogram',
    compileMode: 'bundle',

    // web 端配置项，下方介绍的配置项都将在这里进行配置
    web: {}
  }
])

**Comment by lyfeyaj** [comment]
版本 `@morjs/cli@1.0.49` 中已增加对该特性的多端支持和适配
