### ISSUE TITLE
【eslint配置没有生效】脚手架初始化项目，eslint配置没有生效

### ISSUE THREAD

**Issue by jiang-gary** [eleme/morjs#31]
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/31405035/234807146-568ccb3c-b4b5-4322-8a3b-74dc561dd191.png">

使用`eslint --print-config ./.eslintrc`检测eslint配置文件  发生报错  是规则冲突了 
本地去除规则"prettier/@typescript-eslint"
eslint就能正常运行
<img width="514" alt="image" src="https://user-images.githubusercontent.com/31405035/234807570-2c637228-617d-436c-b520-6033afb9aceb.png">

**Comment by BboyZaki** [comment]
1.0.48 版本已修复
