### ISSUE TITLE
Click event not responding after converting a miniprogram from Wechat type to Alipay type.

### ISSUE THREAD

**Issue by Arvin-xc** [eleme/morjs#36]
**Describe the bug**
Click event not responding after converting a miniprogram from Wechat type to Alipay type.

**To Reproduce**
1、Download the [demo](https://github.com/eleme/morjs/files/11404226/morjs-wx-alipay.zip) and install dependencies.
2、Run script  ```npm run dev```  to convert the miniprogram to an alipay type.
3、Open converted project folder with Alipay IDE.
4、Click the button "返回" at the upper left corner.

**Expected behavior**
It show toast "点击返回"

**Screenshots**
None

**Alipay IDE**
 - OS: Mac OS
 - Version 3.6.3

**Comment by BboyZaki** [comment]
1.0.42 版本已修复，请重装或更新 @morjs/cli 依赖
