### ISSUE TITLE
支付宝组件指定默认抽象节点配置并且同时在多个分包引入时出现报错及生命周期无法执行

### ISSUE THREAD

**Issue by Tuuu** [eleme/morjs#69]
**Describe the bug**
支付宝组件指定默认抽象节点配置并且同时在多个原生分包引入时出现报错及生命周期无法执行。报错内容 “Component() 构造器被调用多次”。

**To Reproduce**
1. yarn create mor  - 小程序分包 - 微信 DSL
2. 创建任意一个自定义组件 user-name，以及**默认抽象节点组件** default-greneric，同时 user-name 需要通过 componentGenerics 配置引入 default-greneric
3. 通过 customEntries.components 指定 user-name 的路径，可以使其编译到产物中（这时可以移除 pages/ 和 app.ts）。也可以在 pages/index/index 引入 user-name
4. 使用支付宝小程序开发者工具创建空白模版，并创建两个分包及对应的页面 packageA/user/index、packageC/user/index，页面需要分别引入 user-name (需要通过**复制**，实际中是每个分包都会安装一份 npm 包)
5. 依次跳转到 packageA packageB 对应的页面，先跳转的分包对应的 user-name 组件一切正常，而且没有控制台报错，后跳转的分包都会在支付宝开发者工具中出现 “Component() 构造器被调用多次” 的报错，同时对应的 user-name 组件的 lifetime.attached 没有执行，截图中 "username component attached" 为 log

**Expected behavior**
无报错及 user-name 组件的生命周期可以正常执行

**Screenshots**
![指定抽象节点配置.png](https://s2.loli.net/2023/07/01/p6QvEdMisnjA4zC.png)

**Desktop (please complete the following information):**
 - 小程序开发者工具: 3.6.4
 - 基础库 2.8.8

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.4

**Additional context**
- mor.config
```js
[
  {
    name: 'wechat-subpackage',
    sourceType: 'wechat',
    target: 'wechat',
    compileType: 'subpackage',
    compileMode: 'bundle',
    autoClean:true,
    jsMinimizer: 'esbuild',
  },
  {
    name: 'alipay-subpackage',
    sourceType: 'wechat',
    target: 'alipay',
    compileType: 'subpackage',
    compileMode: 'bundle',
    autoClean:true,
    jsMinimizer: 'esbuild',
  },
]
```

**Comment by BboyZaki** [comment]
由于不同分包使用了同一个产物资源导致，几种解决方案如下：
1. 分包接入 MorJS；
2. 把引用产物放于主包，各个分包引入主包资源；
3. 编译产物时修改项目 package.json 的 name 或配置 webpackChain 的 chunkLoadingGlobal 方法，使不同分包使用的资源名称不冲突
