### ISSUE TITLE
autoInjectRuntime.api配置为true，组件代码内有“wx”字符串时，转译成web端报错

### ISSUE THREAD

**Issue by mufengfang** [eleme/morjs#81]
**问题描述**
autoInjectRuntime.api配置为true，组件代码内有“wx”字符串时，转译成web端报错

**环境信息**
 - "@morjs/cli": "1.0.68"
- "@morjs/core": "1.0.68"

**Comment by lyfeyaj** [comment]
Fixed in PR #82
