### ISSUE TITLE
要如何新建morJS工程的，官方文档的操作指令对不上

### ISSUE THREAD

**Issue by zhiyi10** [eleme/morjs#85]
执行`mor init`只有以下选择
```
mor init
? 请选择工程类型 › - Use arrow-keys. Return to submit.
❯   小程序
    小程序插件
    小程序分包
    MorJS 工程插件
    MorJS 运行时插件
    MorJS 运行时解决方案
    MorJS 多端组件库
    MorJS 自定义脚手架
```

官方文档（`https://mor.eleme.io/web/basic/quickstart`）如下，没有`MorJS 标准小程序工程`可以选择，是文档没更新，还是框架对小程序转web的能力暂不支持的
```
npm i @morjs/cli -g # 全局安装 MorJS cli(如已安装可跳过)
mor init # 选择 MorJS 标准小程序工程，然后填写信息，在填写 投放渠道 这一项时将 Web 选中
npm run dev:web # 运行项目，控制台会打印地址和二维码
```

**Comment by zhiyi10** [comment]
或者我新建的`微信小程序 DSL`可以通过配置构建出web端的代码吗，主要是想看下微信小程序代码转web代码的完成度如何

**Comment by hwaphon** [comment]
开源版本的 morjs 脚手架没有内置直接创建 web 的功能，建议你这边先按照 [已有 Mor 工程](https://mor.eleme.io/web/basic/quickstart/#%E5%B7%B2%E6%9C%89-morjs-%E5%B7%A5%E7%A8%8B) 的步骤进行操作。

**Comment by hwaphon** [comment]
具体可以参考这个[微信小程序工程](https://github.com/eleme/morjs/tree/main/examples/wechat)，项目拉到本地运行 npm i && npm run dev:web。

**Comment by zhiyi10** [comment]
> 具体可以参考这个[微信小程序工程](https://github.com/eleme/morjs/tree/main/examples/wechat)，项目拉到本地运行 npm i && npm run dev:web。

好的我试下
