### ISSUE TITLE
安装依赖并构建报错

### ISSUE THREAD

**Issue by zhugenqiang** [eleme/morjs#96]
环境：
morjs:master 分支
操作系统windows11
nvm
node: 16.14.0
pnpm: 7.33.6
报错如下：
构建失败！错误信息如下👇🏻
错误信息: Command failed with exit code 2: tsc
src/runtime/public/component.tsx(467,17): error TS2339: Property 'props' does not exist on type 'ReactNode'.
  Property 'props' does not exist on type 'string'.
src/runtime/public/component.tsx(467,28): error TS2339: Property 'props' does not exist on type 'ReactNode'.
  Property 'props' does not exist on type 'string'.
src/runtime/public/component.tsx(468,22): error TS2339: Property 'props' does not exist on type 'ReactNode'.
  Property 'props' does not exist on type 'string'.
错误堆栈: Error: Command failed with exit code 2: tsc
src/runtime/public/component.tsx(467,17): error TS2339: Property 'props' does not exist on type 'ReactNode'.
  Property 'props' does not exist on type 'string'.
src/runtime/public/component.tsx(467,28): error TS2339: Property 'props' does not exist on type 'ReactNode'.
  Property 'props' does not exist on type 'string'.
src/runtime/public/component.tsx(468,22): error TS2339: Property 'props' does not exist on type 'ReactNode'.
  Property 'props' does not exist on type 'string'.
    at makeError (C:\code\mini\morjs\node_modules\.pnpm\execa@5.1.1\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\code\mini\morjs\node_modules\.pnpm\execa@5.1.1\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async build (C:\code\mini\morjs\scripts\build.js:72:5)
    at async Promise.all (index 1)
    at async buildAll (C:\code\mini\morjs\scripts\build.js:113:5)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by hwaphon** [comment]
已收到问题，大概2-3天排查后回复。

**Comment by hwaphon** [comment]
建议先使用 npm、yarn 进行开发，排查下来多个版本的 pnpm 都存在一些问题，后面解决了再同步。
